### ISSUE TITLE
package.json has incorrect main field

### ISSUE THREAD

**Issue by crohlfs** [Daninet/buffer-collection#3]
Hi there. Thanks for the great package, it has been working well.

I just updated to the typescript version and the main field points to `index.ts` causing it to no longer work, changing it to `index.js` seems to fix the issue.
https://github.com/Daninet/buffer-collection/blob/7f795419f1211841ea60d33e876cd7a24885ebb9/package.json#L5

**Comment by Daninet** [comment]
Hey Chris. Thank you.

I've published a new version with fixed main path.
